site_name: IRIS Embedded Python Wrapper
site_description: This project is a wrapper to easily configure and use the Embedded Python feature of InterSystems IRIS in an native way.
site_author: grongier@intersystems.com 
site_url: https://grongierisc.github.io/iris-embedded-python-wrapper/
docs_dir: docs
nav:
  - Home: index.md

theme: readthedocs